#!/bin/bash
# ============================================================
#  GET ACTIVE ENV - Get current active environment
#  Usage: source ~/.local/s1barch/scripts/detection/get_active_env.sh
#  Output: Current environment name
#  ============================================================

set -euo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common/functions.sh"
source "$SCRIPT_DIR/../common/logger.sh"
source "$SCRIPT_DIR/../common/colors.sh"

# Get current environment from config file
CURRENT_ENV_FILE="$S1B_ROOT/config/current_env.yaml"

get_env() {
    if [ ! -f "$CURRENT_ENV_FILE" ]; then
        # File doesn't exist, try to detect
        local detected
        detected=$(source "$SCRIPT_DIR/detect_env.sh" && main desktop)
        
        # Map to environment name
        case "$detected" in
            dwm)
                echo "dwm"
                ;;
            hyprland|waybar)
                echo "waybar"
                ;;
            *)
                echo "auto"
                ;;
        esac
    else
        # Read from config file
        cat "$CURRENT_ENV_FILE" | grep "^current:" | cut -d: -f2 | tr -d ' '
    fi
}

get_env_full() {
    local env
    env=$(get_env)
    
    # Get full env info
    local desktop display_server compositor
    IFS=':' read -r desktop display_server compositor <<< "$(source "$SCRIPT_DIR/detect_env.sh" && main info)"
    
    echo "$env"
    echo "desktop: $desktop"
    echo "display_server: $display_server"
    echo "compositor: $compositor"
}

set_env() {
    local env="$1"
    
    if [ -z "$env" ]; then
        log_error "Environment name required"
        return 1
    fi
    
    # Validate environment name
    case "$env" in
        dwm|waybar|auto)
            ;;
        *)
            log_error "Invalid environment: $env (use: dwm|waybar|auto)"
            return 1
            ;;
    esac
    
    # Ensure config directory exists
    ensure_dir_exists "$(dirname "$CURRENT_ENV_FILE")"
    
    # Set variables for the config file
    local last_switch last_sync desktop display_server compositor
    last_switch=$(date -Iseconds)
    last_sync=$(date -Iseconds)
    desktop=$(source "$SCRIPT_DIR/detect_env.sh" && main desktop)
    display_server=$(source "$SCRIPT_DIR/detect_env.sh" && main display)
    compositor=$(source "$SCRIPT_DIR/detect_env.sh" && main compositor)
    
    # Update config file
    cat > "$CURRENT_ENV_FILE" << EOF
# S1Bs1stem Current Environment
# Auto-generated by S1Bs1stem

current: ${env}
last_switch: ${last_switch}
last_sync: ${last_sync}
desktop: ${desktop}
display_server: ${display_server}
compositor: ${compositor}
EOF
    
    log_success "Environment set to: $env"
}

is_env_active() {
    local target_env="$1"
    local current_env
    current_env=$(get_env)
    
    [ "$current_env" = "$target_env" ]
}

# Main function
main() {
    local action="${1:-get}"
    local env_name="$2"
    
    case "$action" in
        get|env|current)
            get_env
            ;;
        full|info|details)
            get_env_full
            ;;
        set|switch)
            set_env "$env_name"
            ;;
        check|verify|is)
            if is_env_active "$env_name"; then
                return 0
            else
                return 1
            fi
            ;;
        *)
            log_error "Invalid action: $action"
            echo "Usage: $0 [get|full|set|check] [env_name]"
            exit 1
            ;;
    esac
}

# Run main if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi

# Export functions for sourcing
export -f get_env
export -f get_env_full
export -f set_env
export -f is_env_active
export -f main
