#!/bin/bash
# ============================================================
#  DWM SETUP
#  Install and configure DWM window manager
#  ============================================================

set -euo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../scripts/common/functions.sh"
source "$SCRIPT_DIR/../../scripts/common/logger.sh"
source "$SCRIPT_DIR/../../scripts/common/colors.sh"

log_info "Setting up DWM window manager..."

# Check if DWM source exists
DWM_CONFIG_DIR="$HOME/.config/dwm"
DWM_SOURCE_DIR="$S1B_ROOT/configs/dwm"

if [ ! -d "$DWM_SOURCE_DIR" ]; then
    log_warn "DWM source directory not found: $DWM_SOURCE_DIR"
    log_info "DWM will be installed from dotfiles-s1b if available"
    
    # Try to find DWM in dotfiles-s1b
    if [ -d "$HOME/Desktop/dotfiles-s1b/.config/dwm" ]; then
        DWM_SOURCE_DIR="$HOME/Desktop/dotfiles-s1b/.config/dwm"
        log_info "Found DWM config in dotfiles-s1b"
    fi
fi

# Create DWM config directory
ensure_dir_exists "$DWM_CONFIG_DIR"

# Backup existing DWM config
if [ -d "$DWM_CONFIG_DIR" ]; then
    backup=$(backup_dir "$DWM_CONFIG_DIR")
    log_info "Backed up existing DWM config to: $backup"
fi

# Copy DWM configuration
if [ -d "$DWM_SOURCE_DIR" ]; then
    log_info "Copying DWM configuration..."
    cp -r "$DWM_SOURCE_DIR/"* "$DWM_CONFIG_DIR/"
    log_success "DWM configuration copied"
else
    log_warn "DWM configuration not found, skipping..."
fi

# Check DWM dependencies
log_info "Checking DWM dependencies..."

dwm_deps=(
    "libx11"
    "libxft"
    "libxinerama"
    "libxcb"
    "xcb-util"
    "xcb-util-wm"
)

for dep in "${dwm_deps[@]}"; do
    if is_package_installed "$dep"; then
        log_success "$dep is installed"
    else
        log_warn "$dep is not installed"
    fi
done

# Install DWM if not installed
if ! command -v dwm &>/dev/null; then
    log_info "DWM not found, installation required"
    log_info "Please install DWM using your dotfiles-s1b setup"
    log_info "Or compile DWM from source in: $DWM_CONFIG_DIR"
else
    log_success "DWM is installed: $(command -v dwm)"
fi

# Setup DWM autostart
log_info "Setting up DWM autostart..."

AUTOSTART_DIR="$HOME/.config/autostart"
ensure_dir_exists "$AUTOSTART_DIR"

AUTOSTART_SCRIPT="$AUTOSTART_DIR/dwm-autostart.sh"

cat > "$AUTOSTART_SCRIPT" << 'EOF'
#!/bin/bash
# DWM Autostart Script
# Generated by S1Bs1stem

# Start Waybar
if command -v waybar &>/dev/null; then
    waybar &
fi

# Start Picom (compositor)
if command -v picom &>/dev/null; then
    picom &
fi

# Start Dunst (notifications)
if command -v dunst &>/dev/null; then
    dunst &
fi

# Start network applet
if command -v nm-applet &>/dev/null; then
    nm-applet &
fi

# Start Bluetooth applet
if command -v blueman-applet &>/dev/null; then
    blueman-applet &
fi

# Start clipboard manager
if command -v clipmenud &>/dev/null; then
    clipmenud &
fi
EOF

chmod +x "$AUTOSTART_SCRIPT"
log_success "DWM autostart script created"

log_success "DWM setup completed"
exit 0
