#!/bin/bash
# ============================================================
#  TO DWM - Switch to DWM environment
#  Usage: bash ~/Desktop/S1Bs1stem/scripts/env_switcher/to_dwm.sh
#  ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common/functions.sh"
source "$SCRIPT_DIR/../common/logger.sh"
source "$SCRIPT_DIR/../common/colors.sh"

log_info "Switching to DWM environment..."

# 1. Detectar si estamos en Wayland
if [ -n "$WAYLAND_DISPLAY" ]; then
    log_info "Currently on Wayland, preparing to switch to DWM..."
else
    log_warn "Already on X11, checking DWM status..."
fi

# 2. Matar servicios Wayland
log_info "Stopping Wayland services..."
if pgrep -x waybar &>/dev/null; then
    log_info "  - Stopping waybar..."
    killall waybar
fi

if pgrep -x hyprland &>/dev/null; then
    log_info "  - Stopping hyprland..."
    killall hyprland
fi

if pgrep -x kwin &>/dev/null; then
    log_info "  - Stopping kwin..."
    killall kwin
fi

# 3. Actualizar current_env.yaml
CURRENT_ENV_FILE="$HOME/Desktop/S1Bs1stem/config/current_env.yaml"
ensure_dir_exists "$(dirname "$CURRENT_ENV_FILE")"

cat > "$CURRENT_ENV_FILE" << 'EOF'
# S1Bs1stem Current Environment
# Auto-generated by S1Bs1stem

current: dwm
last_switch: $(date -Iseconds)
desktop: dwm
display_server: x11
compositor: picom
last_sync: $(date -Iseconds)
EOF

log_success "Environment updated to DWM"

# 4. Sincronizar configs desde dotfiles-s1b
SYNC_SCRIPT="$HOME/Desktop/S1Bs1stem/scripts/sync/sync_from_s1b.sh"

if [ -f "$SYNC_SCRIPT" ]; then
    log_info "Syncing DWM config from dotfiles-s1b..."
    bash "$SYNC_SCRIPT" dwm
else
    log_warn "Sync script not found, skipping..."
fi

# 5. Preparar para logout X11
log_info "Preparing for X11 logout..."
log_info "You will be logged out in 3 seconds..."
log_info "DWM will start on re-login"

# 6. Logout X11 (requiere relogin)
sleep 3

log_info "Logging out to start DWM..."
pkill -9 Xorg || pkill -9 X || logout

# Si llegamos aquí, algo salió mal
log_error "Logout failed or was cancelled"
exit 1
