#!/bin/bash
# ============================================================
#  TO WAYLAND - Switch to Wayland/Waybar
#  Usage: bash ~/Desktop/S1Bs1stem/scripts/env_switcher/to_wayland.sh
#  ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common/functions.sh"
source "$SCRIPT_DIR/../common/logger.sh"
source "$SCRIPT_DIR/../common/colors.sh"

log_info "Switching to Wayland environment..."

# 1. Detectar si estamos en DWM
if pgrep -x dwm &>/dev/null; then
    log_info "Currently on DWM (X11), preparing to switch to Wayland..."
else
    log_warn "Already on Wayland or unknown session"
fi

# 2. Matar servicios DWM X11
log_info "Stopping DWM (X11)..."
if pgrep -x dwm &>/dev/null; then
    log_info "  - Stopping dwm..."
    killall dwm
fi

# 3. Matar X11 para limpiar
if [ -n "$DISPLAY" ]; then
    log_info "  - Killing Xorg session..."
    pkill -9 Xorg || true
fi

# 4. Actualizar current_env.yaml
CURRENT_ENV_FILE="$S1B_ROOT/config/current_env.yaml"
ensure_dir_exists "$(dirname "$CURRENT_ENV_FILE")"

cat > "$CURRENT_ENV_FILE" << 'EOF'
# S1Bs1stem Current Environment
# Auto-generated by S1Bs1stem

current: wayland
last_switch: $(date -Iseconds)
desktop: waybar
display_server: wayland
compositor: waybar
last_sync: $(date -Iseconds)
EOF

log_success "Environment updated to Wayland"

# 5. Sincronizar configs desde dotfiles-s1b
SYNC_SCRIPT="$S1B_ROOT/scripts/sync/sync_from_s1b.sh"

if [ -f "$SYNC_SCRIPT" ]; then
    log_info "Syncing Waybar config from dotfiles-s1b..."
    bash "$SYNC_SCRIPT" waybar
else
    log_warn "Sync script not found, skipping..."
fi

# 6. Preparar para iniciar sesión Wayland
log_info "Preparing for Wayland login..."
log_info "You can start Wayland by logging out and logging in"

# 7. No hacer logout automático, solo sincronizar
log_success "Wayland environment ready for login"
log_info "Log out and log in to start Wayland/Waybar"
